import path from "path";
import { TechnologyOption } from "../../core";
import { resolveTemplatesRoot } from "../template-root";
import { InitPromptData } from "../types";

const featureTemplateRoot = (...segments: string[]): string =>
  path.join(resolveTemplatesRoot(__dirname), "features", ...segments);

export const featureOptions: TechnologyOption<InitPromptData>[] = [
  {
    id: "docker",
    label: "Docker",
    description: "Generates Dockerfile, .dockerignore, and docker-compose.yml",
    contribute: (context) => ({
      templateRoots: [featureTemplateRoot("runtime", "docker")],
      templateData: {
        docker: {
          includesDatabase: context.has("prisma") || context.has("typeorm") || context.has("sequelize"),
          includesRedis: context.has("redis") || context.has("bullmq"),
        },
      },
      packageJson: {
        scripts: {
          "docker:build": "docker compose build",
          "docker:up": "docker compose up --build",
          "docker:down": "docker compose down",
        },
      },
    }),
  },
  {
    id: "redis",
    label: "Redis",
    description: "Adds REDIS_URL and shared Redis runtime settings",
    contribute: (context) => ({
      packageJson: {
        dependencies: {
          "@nestjs-modules/ioredis": "^2.2.1",
          ioredis: "^5.10.1",
        },
      },
      slots: {
        "env.entries": [
          `REDIS_URL="redis://${context.has("docker") ? "redis" : "localhost"}:6379"`,
        ],
      },
    }),
  },
  {
    id: "bullmq",
    label: "BullMQ",
    description: "Adds queue infrastructure and automatically includes Redis",
    requires: ["redis"],
    contribute: () => ({
      packageJson: {
        dependencies: {
          "@nestjs/bullmq": "^11.0.4",
          bullmq: "^5.76.4",
        },
      },
    }),
  },
  {
    id: "throttler",
    label: "Throttler",
    description: "Configures global request throttling",
    contribute: (context) => ({
      packageJson: {
        dependencies: {
          ...(context.has("redis")
            ? {
                "@nest-lab/throttler-storage-redis": "^1.2.0",
              }
            : {}),
          "@nestjs/throttler": "^6.5.0",
        },
      },
    }),
  },
  {
    id: "swagger",
    label: "Swagger",
    description: "Bootstraps OpenAPI docs under /docs",
    contribute: () => ({
      slots: {
        "main.imports": [
          "import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';",
        ],
        "main.bootstrap": [
          "const swaggerConfig = new DocumentBuilder().setTitle('API Docs').setDescription('Generated by skelenest').setVersion('1.0.0').build();",
          "const swaggerDocument = SwaggerModule.createDocument(app, swaggerConfig);",
          "SwaggerModule.setup('docs', app, swaggerDocument);",
        ],
      },
      packageJson: {
        dependencies: {
          "@nestjs/swagger": "^11.2.0",
        },
      },
    }),
  },
  {
    id: "auth",
    label: "Auth Starter Skeleton",
    description: "Adds a minimal auth module skeleton for future expansion",
    contribute: () => ({
      templateRoots: [featureTemplateRoot("security", "auth")],
      slots: {
        "app.module.imports": [
          "import { AuthModule } from './auth/auth.module';",
        ],
        "app.module.moduleImports": ["AuthModule"],
      },
    }),
  },
];
